apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: csharpsm
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/knative-samples/helloworld-csharp:latest
